-- MySQL Script generated by MySQL Workbench
-- Fri Feb 15 14:38:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema leavingLetter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `leavingLetter` ;

-- -----------------------------------------------------
-- Schema leavingLetter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `leavingLetter` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `leavingLetter` ;

-- -----------------------------------------------------
-- Table `leavingLetter`.`userPermission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leavingLetter`.`userPermission` ;

CREATE TABLE IF NOT EXISTS `leavingLetter`.`userPermission` (
  `fId` VARCHAR(5) NOT NULL,
  `fUserType` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fId`),
  UNIQUE INDEX `fId_UNIQUE` (`fId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leavingLetter`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leavingLetter`.`positions` ;

CREATE TABLE IF NOT EXISTS `leavingLetter`.`positions` (
  `fId` VARCHAR(5) NOT NULL,
  `fPosName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fId`),
  UNIQUE INDEX `fId_UNIQUE` (`fId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leavingLetter`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leavingLetter`.`users` ;

CREATE TABLE IF NOT EXISTS `leavingLetter`.`users` (
  `fId` VARCHAR(10) NOT NULL,
  `fFirstName` VARCHAR(30) NOT NULL,
  `fLastName` VARCHAR(30) NOT NULL,
  `fBday` DATETIME NOT NULL,
  `fPosition` VARCHAR(5) NOT NULL,
  `fAddress` VARCHAR(100) NOT NULL,
  `fPhone` VARCHAR(10) NOT NULL,
  `fTeamId` VARCHAR(5) NOT NULL,
  `fTypeId` VARCHAR(5) NOT NULL,
  `fEmail` VARCHAR(45) NOT NULL,
  `fPassword` VARCHAR(20) NOT NULL,
  `fUsername` VARCHAR(45) NOT NULL,
  `fUsername` VARCHAR(5) NOT NULL,
  `positions_fId` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`fId`),
  UNIQUE INDEX `fId_UNIQUE` (`fId` ASC) VISIBLE,
  INDEX `fk_users_userPermission1_idx` (`fUsername` ASC) VISIBLE,
  INDEX `fk_users_positions1_idx` (`positions_fId` ASC) VISIBLE,
  CONSTRAINT `fk_users_userPermission1`
    FOREIGN KEY (`fUsername`)
    REFERENCES `leavingLetter`.`userPermission` (`fId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_positions1`
    FOREIGN KEY (`positions_fId`)
    REFERENCES `leavingLetter`.`positions` (`fId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leavingLetter`.`teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leavingLetter`.`teams` ;

CREATE TABLE IF NOT EXISTS `leavingLetter`.`teams` (
  `fId` VARCHAR(5) NOT NULL,
  `fTeamName` VARCHAR(45) NOT NULL,
  `fTeamLead` VARCHAR(10) NOT NULL,
  `users_fId` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`fId`),
  UNIQUE INDEX `fId_UNIQUE` (`fId` ASC) VISIBLE,
  INDEX `fk_teams_users1_idx` (`users_fId` ASC) VISIBLE,
  CONSTRAINT `fk_teams_users1`
    FOREIGN KEY (`users_fId`)
    REFERENCES `leavingLetter`.`users` (`fId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leavingLetter`.`absenceTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leavingLetter`.`absenceTypes` ;

CREATE TABLE IF NOT EXISTS `leavingLetter`.`absenceTypes` (
  `fId` INT NOT NULL,
  `fAbsenceTypeName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leavingLetter`.`leaveLetters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leavingLetter`.`leaveLetters` ;

CREATE TABLE IF NOT EXISTS `leavingLetter`.`leaveLetters` (
  `fId` VARCHAR(10) NOT NULL,
  `fRdt` DATETIME NOT NULL,
  `fFromDT` DATETIME NOT NULL,
  `fToDT` DATETIME NOT NULL,
  `fAbsenceType` INT NOT NULL,
  `fSubstituteId` VARCHAR(10) NULL,
  `fUserId` VARCHAR(45) NOT NULL,
  `users_fId` VARCHAR(10) NOT NULL,
  `users_fId1` VARCHAR(10) NOT NULL,
  `absenceTypes_fId` INT NOT NULL,
  `fStatus` INT NOT NULL,
  PRIMARY KEY (`fId`),
  UNIQUE INDEX `fId_UNIQUE` (`fId` ASC) VISIBLE,
  INDEX `fk_leaveLetters_users_idx` (`users_fId` ASC) VISIBLE,
  INDEX `fk_leaveLetters_users1_idx` (`users_fId1` ASC) VISIBLE,
  INDEX `fk_leaveLetters_absenceTypes1_idx` (`absenceTypes_fId` ASC) VISIBLE,
  CONSTRAINT `fk_leaveLetters_users`
    FOREIGN KEY (`users_fId`)
    REFERENCES `leavingLetter`.`users` (`fId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leaveLetters_users1`
    FOREIGN KEY (`users_fId1`)
    REFERENCES `leavingLetter`.`users` (`fId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leaveLetters_absenceTypes1`
    FOREIGN KEY (`absenceTypes_fId`)
    REFERENCES `leavingLetter`.`absenceTypes` (`fId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leavingLetter`.`userRefToken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leavingLetter`.`userRefToken` ;

CREATE TABLE IF NOT EXISTS `leavingLetter`.`userRefToken` (
  `fUserId` VARCHAR(10) NOT NULL,
  `fRefToken` VARCHAR(20) NOT NULL,
  `fRdt` DATETIME NOT NULL,
  `users_fId` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`fUserId`),
  UNIQUE INDEX `fUserId_UNIQUE` (`fUserId` ASC) VISIBLE,
  INDEX `fk_userRefToken_users1_idx` (`users_fId` ASC) VISIBLE,
  CONSTRAINT `fk_userRefToken_users1`
    FOREIGN KEY (`users_fId`)
    REFERENCES `leavingLetter`.`users` (`fId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leavingLetter`.`users_has_teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leavingLetter`.`users_has_teams` ;

CREATE TABLE IF NOT EXISTS `leavingLetter`.`users_has_teams` (
  `users_fId` VARCHAR(10) NOT NULL,
  `teams_fId` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`users_fId`, `teams_fId`),
  INDEX `fk_users_has_teams_teams1_idx` (`teams_fId` ASC) VISIBLE,
  INDEX `fk_users_has_teams_users1_idx` (`users_fId` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_teams_users1`
    FOREIGN KEY (`users_fId`)
    REFERENCES `leavingLetter`.`users` (`fId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_teams_teams1`
    FOREIGN KEY (`teams_fId`)
    REFERENCES `leavingLetter`.`teams` (`fId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `leavingLetter`.`rejectedLetterDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `leavingLetter`.`rejectedLetterDetail` ;

CREATE TABLE IF NOT EXISTS `leavingLetter`.`rejectedLetterDetail` (
  `fLetterId` VARCHAR(10) NOT NULL,
  `fReason` VARCHAR(45) NOT NULL,
  `fRejectType` INT NOT NULL,
  `leaveLetters_fId` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`fLetterId`),
  INDEX `fk_rejectedLetterDetail_leaveLetters1_idx` (`leaveLetters_fId` ASC) VISIBLE,
  CONSTRAINT `fk_rejectedLetterDetail_leaveLetters1`
    FOREIGN KEY (`leaveLetters_fId`)
    REFERENCES `leavingLetter`.`leaveLetters` (`fId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
